# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0003_jointrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jointotrip', to='travel_buddy.Trip'),
        ),
        migrations.AlterField(
            model_name='jointrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jointouser', to='travel_buddy.User'),
        ),
    ]
